openapi: 3.0.2
info:
  title: Name Resolver
  version: 1.6.1
  email: bizon@renci.org
  name: Chris Bizon
  x-id: https://github.com/cbizon
  x-role: responsible developer
  description: 'Name Resolver (Name Lookup) service<p/>This service takes lexical strings and attempts to map them to identifiers
    (CURIEs) from a vocabulary or ontology. An optional autocomplete mode (which assumes the query is incomplete) is available,
    along with many other options. Given a preferred CURIE, the known synonyms of that CURIE can also be retrieved.<p/>
    Multiple results may be returned representing possible conceptual matches, but all of the identifiers
    have been correctly normalized using the
    <a href="https://github.com/NCATSTranslator/NodeNormalization">Node Normalization</a> service.<p/>You can read more
    about this API on the <a href="https://github.com/NCATSTranslator/NameResolution">NameResolution GitHub repository</a>.<p/>
    Note that the returned by this service have been conflated using both GeneProtein and DrugChemical conflation;
    you can read more about this at the <a href="https://github.com/NCATSTranslator/Babel/blob/master/docs/Conflation.md">Conflation documentation</a>.'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://toss.apps.renci.org/tos?service_long=Name+Resolver&provider_long=the+Translator+Consortium
  x-translator:
    component: Utility
    team:
      - Standards Reference Implementation Team
    infores: infores:sri-name-resolver
servers:
  - description: Default server
    url: https://name-resolution-sri.renci.org/
  - description: localhost
    url: http://localhost:2433/
tags:
  - name: translator
